public class MapMaker {

    private String[][] map;
    private int rows;
    private int columns;
    private int randDangerRow;
    private int randDangerCol;
    private int counter;

    public MapMaker() {
        counter = 0;
        rows = 5;
        columns = 21;
        map = new String[rows][columns];
        for (int rows = 0; rows < this.rows; rows++){
            for (int columns = 0; columns < this.columns; columns++){
                if (columns == 0){
                    map[rows][columns] = "~";
                } else {
                    map[rows][columns] = "-";
                }
            }
        }
    }

    public void increaseCounter(){
        counter++;
    }

    public void printMap(){
        for (int rows = 0; rows < 5; rows++){
            for (int columns = 0; columns < 20; columns++){
                System.out.print(map[rows][columns]);
            }
            System.out.println();
        }
    }

    public void setCoord(int x, int y, String str){
        map[y][x] = str;
    }

    public String getCurIndex(int x, int y){
        return map[y][x];
    }

    public int getMaxRows(){
        return rows;
    }

    public int getMaxColumns(){
        return columns;
    }

    //depending on counter, goes through the various stages of hazards with the makeHazardx variables.
    public void hazardTracker(){
        if (counter == 2){
            makeHazard1();
        }
        if (counter == 3){
            makeHazard2();
        }
        if (counter == 4){
            makeHazard3();
        }
        if (counter == 5){
            clearHazard();
        }
        if (counter == 6){
            counter = 0;
        }
    }

    //generates a random starting position (top left corner of the hazard area),
    //then in a 3x8 area, puts ! to warn the player
    private void makeHazard1(){
        randDangerRow = (int) (Math.random() * 3);
        randDangerCol = (int) (Math.random() * 13) + 1;
        for (int row = randDangerRow; row < randDangerRow + 3; row++){
            for (int col = randDangerCol; col < randDangerCol + 8; col++){
                map[row][col] = "!";
            }
        }
    }

    //in the same area generated by makeHazard1, replace ! with " " as a last chance for the player to escape.
    private void makeHazard2(){
        for (int row = randDangerRow; row < randDangerRow + 3; row++){
            for (int col = randDangerCol; col < randDangerCol + 8; col++){
                map[row][col] = " ";
            }
        }
    }

    //in the same area as makeHazard1, place Os, which will kill the player on contact
    //(above interaction handled in Game class with checkTile method)
    private void makeHazard3(){
        for (int row = randDangerRow; row < randDangerRow + 3; row++){
            for (int col = randDangerCol; col < randDangerCol + 8; col++){
                map[row][col] = "O";
            }
        }
    }

    //replace Os in hazard area with the normal bg, "-", to return map to normal.
    private void clearHazard(){
        for (int row = randDangerRow; row < randDangerRow + 3; row++){
            for (int col = randDangerCol; col < randDangerCol + 8; col++){
                map[row][col] = "-";
            }
        }
    }
}